# Generated by Django 3.2.16 on 2023-05-27 15:32

import apps.contacts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_cumpleanos', models.DateField(blank=True, null=True)),
                ('redes_sociales', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.contacts.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacto')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto', to='contacts.image'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
