# Generated by Django 3.2.16 on 2023-05-30 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_alter_contacto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
            preserve_default=False,
        ),
    ]
