# Generated by Django 3.2.16 on 2023-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='access_code',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='miguelegocheaga8@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
